In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Import data
delivery_data = pd.read_csv("../data/olist_delivery_time_data.csv")
delivery_data.head()

,order_id,purchase_dayofweek,purchase_month,purchase_hour,purchase_is_weekend,estimated_delivery_days,n_items,n_sellers,total_price,total_freight,...,product_width_cm,payment_installments,payment_value,payment_type,customer_state,seller_state,product_category_name_english,distance_km,same_state,delivery_time_days
0,e481f51cbdc54678b7cc49136f2d6af7,0,10,10,0,15.544063,1,1,29.99,8.72,...,13.0,1.0,38.71,voucher,SP,SP,housewares,18.681711,1,8.436574
1,53cdb2fc8bc7dce0b6741e2150273451,1,7,20,0,19.137766,1,1,118.70,22.76,...,19.0,1.0,141.46,boleto,BA,SP,perfumery,861.035367,0,13.782037
2,47770eb9100c2d0c44946d9cf07ec65d,2,8,8,0,26.639711,1,1,159.90,19.22,...,21.0,3.0,179.12,credit_card,GO,SP,auto,514.547140,0,9.394213
3,949d5b44dbf5de918fe9c16f97b45f8a,5,11,19,1,26.188819,1,1,45.00,27.20,...,20.0,1.0,72.20,credit_card,RN,MG,pet_shop,1821.802656,0,13.208750
4,ad21c59c0840e6cb83a9ceb5573f8159,1,2,21,0,12.112049,1,1,19.90,8.72,...,15.0,1.0,28.62,credit_card,SP,SP,stationery,29.593095,1,2.873877

## Understanding data

In [3]:
print(f"The data has {delivery_data.shape[0]} rows and {delivery_data.shape[1]} columns.")

The data has 96478 rows and 24 columns.

In [4]:
# Structural summary of data
delivery_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 96478 entries, 0 to 96477
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       96478 non-null  str
 1   purchase_dayofweek             96478 non-null  int64
 2   purchase_month                 96478 non-null  int64
 3   purchase_hour                  96478 non-null  int64
 4   purchase_is_weekend            96478 non-null  int64
 5   estimated_delivery_days        96478 non-null  float64
 6   n_items                        96478 non-null  int64
 7   n_sellers                      96478 non-null  int64
 8   total_price                    96478 non-null  float64
 9   total_freight                  96478 non-null  float64
 10  avg_price                      96478 non-null  float64
 11  product_weight_g               96462 non-null  float64
 12  product_length_cm              96462 non-null  float64
 13  product_height_cm              96462 non-null  float64
 14  product_width_cm               96462 non-null  float64
 15  payment_installments           96477 non-null  float64
 16  payment_value                  96477 non-null  float64
 17  payment_type                   96477 non-null  str
 18  customer_state                 96478 non-null  str
 19  seller_state                   96478 non-null  str
 20  product_category_name_english  95100 non-null  str
 21  distance_km                    96000 non-null  float64
 22  same_state                     96478 non-null  int64
 23  delivery_time_days             96470 non-null  float64
dtypes: float64(12), int64(7), str(5)
memory usage: 23.1 MB

In [5]:
# Statistical summary of data
delivery_data.describe()

,purchase_dayofweek,purchase_month,purchase_hour,purchase_is_weekend,estimated_delivery_days,n_items,n_sellers,total_price,total_freight,avg_price,product_weight_g,product_length_cm,product_height_cm,product_width_cm,payment_installments,payment_value,distance_km,same_state,delivery_time_days
count,96478.000000,96478.000000,96478.000000,96478.000000,96478.000000,96478.000000,96478.000000,96478.000000,96478.000000,96478.000000,96462.000000,96462.000000,96462.000000,96462.000000,96477.000000,96477.000000,96000.000000,96478.000000,96470.000000
mean,2.756577,6.031116,14.773192,0.230001,23.736347,1.142198,1.013900,137.041586,22.785253,125.234076,2097.746968,30.093125,16.447803,23.013891,2.928024,159.856357,600.654736,0.359730,12.558217
std,1.967058,3.228391,5.328374,0.420835,8.760765,0.538804,0.123536,209.045198,21.559197,189.698083,3754.111279,16.097278,13.284786,11.723022,2.712723,218.813144,594.146033,0.479924,9.546156
min,0.000000,1.000000,0.000000,0.000000,2.008009,1.000000,1.000000,0.850000,0.000000,0.850000,0.000000,7.000000,2.000000,6.000000,0.000000,9.590000,0.000000,0.000000,0.533414
25%,1.000000,3.000000,11.000000,0.000000,18.330081,1.000000,1.000000,45.900000,13.850000,41.908333,300.000000,18.000000,8.000000,15.000000,1.000000,61.880000,184.972815,0.000000,6.766204
50%,3.000000,6.000000,15.000000,0.000000,23.230880,1.000000,1.000000,86.575000,17.170000,79.000000,700.000000,25.000000,13.000000,20.000000,2.000000,105.280000,433.773044,0.000000,10.217477
75%,4.000000,8.000000,19.000000,0.000000,28.407590,1.000000,1.000000,149.900000,24.017500,139.900000,1800.000000,38.000000,20.000000,30.000000,4.000000,176.330000,798.210166,1.000000,15.720182
max,6.000000,12.000000,23.000000,1.000000,155.135463,21.000000,5.000000,13440.000000,1794.960000,6735.000000,40425.000000,105.000000,105.000000,118.000000,24.000000,13664.080000,8677.859564,1.000000,209.628611

In [6]:
# Columns in data
print("Columns:", delivery_data.columns)

Columns: Index(['order_id', 'purchase_dayofweek', 'purchase_month', 'purchase_hour',
       'purchase_is_weekend', 'estimated_delivery_days', 'n_items',
       'n_sellers', 'total_price', 'total_freight', 'avg_price',
       'product_weight_g', 'product_length_cm', 'product_height_cm',
       'product_width_cm', 'payment_installments', 'payment_value',
       'payment_type', 'customer_state', 'seller_state',
       'product_category_name_english', 'distance_km', 'same_state',
       'delivery_time_days'],
      dtype='str')

In [7]:
# Datatypes in data
delivery_data.dtypes

order_id                             str
purchase_dayofweek                 int64
purchase_month                     int64
purchase_hour                      int64
purchase_is_weekend                int64
estimated_delivery_days          float64
n_items                            int64
n_sellers                          int64
total_price                      float64
total_freight                    float64
avg_price                        float64
product_weight_g                 float64
product_length_cm                float64
product_height_cm                float64
product_width_cm                 float64
payment_installments             float64
payment_value                    float64
payment_type                         str
customer_state                       str
seller_state                         str
product_category_name_english        str
distance_km                      float64
same_state                         int64
delivery_time_days               float64
dtype: object

In [8]:
# Missing values in data
delivery_data.isnull().sum()

order_id                            0
purchase_dayofweek                  0
purchase_month                      0
purchase_hour                       0
purchase_is_weekend                 0
estimated_delivery_days             0
n_items                             0
n_sellers                           0
total_price                         0
total_freight                       0
avg_price                           0
product_weight_g                   16
product_length_cm                  16
product_height_cm                  16
product_width_cm                   16
payment_installments                1
payment_value                       1
payment_type                        1
customer_state                      0
seller_state                        0
product_category_name_english    1378
distance_km                       478
same_state                          0
delivery_time_days                  8
dtype: int64

In [9]:
# Duplicate values in data
delivery_data.duplicated().sum()

np.int64(0)

In [10]:
delivery_data["delivery_time_days"].describe()

count    96470.000000
mean        12.558217
std          9.546156
min          0.533414
25%          6.766204
50%         10.217477
75%         15.720182
max        209.628611
Name: delivery_time_days, dtype: float64

## Data Cleaning

In [11]:
df = delivery_data.copy()

In [12]:
df.isnull().sum()

order_id                            0
purchase_dayofweek                  0
purchase_month                      0
purchase_hour                       0
purchase_is_weekend                 0
estimated_delivery_days             0
n_items                             0
n_sellers                           0
total_price                         0
total_freight                       0
avg_price                           0
product_weight_g                   16
product_length_cm                  16
product_height_cm                  16
product_width_cm                   16
payment_installments                1
payment_value                       1
payment_type                        1
customer_state                      0
seller_state                        0
product_category_name_english    1378
distance_km                       478
same_state                          0
delivery_time_days                  8
dtype: int64

In [13]:
# Removed rows where target is missing
df = df.dropna(subset=["delivery_time_days"])
print("missing target values:", df["delivery_time_days"].isnull().sum())
print("New shape:", df.shape)

missing target values: 0
New shape: (96470, 24)

In [14]:
# Filled numerical values with median because median is robust to outliers
numerical_columns = [
    "product_weight_g", "product_length_cm", "product_height_cm", 
    "product_width_cm", "payment_installments", "payment_value", 
    "distance_km"
]

for column in numerical_columns:
    df[column] = df[column].fillna(df[column].median())

In [15]:
df["product_category_name_english"].value_counts()

product_category_name_english
bed_bath_table               9167
health_beauty                8608
sports_leisure               7490
computers_accessories        6500
furniture_decor              6213
                             ...
arts_and_craftmanship          22
cds_dvds_musicals              12
la_cuisine                     12
fashion_childrens_clothes       7
security_and_services           2
Name: count, Length: 71, dtype: int64

In [16]:
# As product category name was unknown so i filled missing values in product_category_name_english with Unknown
df["product_category_name_english"] = (df["product_category_name_english"].fillna("Unknown"))

In [17]:
df["payment_type"].value_counts()

payment_type
credit_card    73934
boleto         19191
voucher         1861
debit_card      1483
Name: count, dtype: int64

In [18]:
# Well, firstly i thought i should fill it with mode but then i thought it might be misleading so, i filled payment_type with Unknown
df["payment_type"] = df["payment_type"].fillna("Unknown")

In [19]:
# Dropped unnecessary column order_id
df.drop(columns='order_id', inplace=True)

In [20]:
print(df.isnull().sum())

purchase_dayofweek               0
purchase_month                   0
purchase_hour                    0
purchase_is_weekend              0
estimated_delivery_days          0
n_items                          0
n_sellers                        0
total_price                      0
total_freight                    0
avg_price                        0
product_weight_g                 0
product_length_cm                0
product_height_cm                0
product_width_cm                 0
payment_installments             0
payment_value                    0
payment_type                     0
customer_state                   0
seller_state                     0
product_category_name_english    0
distance_km                      0
same_state                       0
delivery_time_days               0
dtype: int64

## Checking for skewness

In [21]:
numerical_columns = df.select_dtypes(include='number')
numerical_columns.skew()

purchase_dayofweek          0.167853
purchase_month              0.207865
purchase_hour              -0.600971
purchase_is_weekend         1.283267
estimated_delivery_days     0.905136
n_items                     7.557602
n_sellers                   9.870271
total_price                 9.885400
total_freight              12.276901
avg_price                   7.869020
product_weight_g            3.611533
product_length_cm           1.766537
product_height_cm           2.266047
product_width_cm            1.717098
payment_installments        1.603697
payment_value               9.366699
distance_km                 1.719469
same_state                  0.584664
delivery_time_days          3.833377
dtype: float64

* skewness > zero -> Right Skewed
* skewness = negative -> Left Skewed

**I will handle skewness in pipeline for n_items, n_sellers, total_price, total_freight, avg_price, product_weight_g, product_length_cm, product_height_cm, product_width_cm, payment_value, distance_km, delivery_time_days**

## Feature Encoding Strategy

In [22]:
df.dtypes

purchase_dayofweek                 int64
purchase_month                     int64
purchase_hour                      int64
purchase_is_weekend                int64
estimated_delivery_days          float64
n_items                            int64
n_sellers                          int64
total_price                      float64
total_freight                    float64
avg_price                        float64
product_weight_g                 float64
product_length_cm                float64
product_height_cm                float64
product_width_cm                 float64
payment_installments             float64
payment_value                    float64
payment_type                         str
customer_state                       str
seller_state                         str
product_category_name_english        str
distance_km                      float64
same_state                         int64
delivery_time_days               float64
dtype: object

In [23]:
df['payment_type'].value_counts()

payment_type
credit_card    73934
boleto         19191
voucher         1861
debit_card      1483
Unknown            1
Name: count, dtype: int64

In [24]:
# Contains 27 unique values 
len(df['customer_state'].value_counts())

27

In [25]:
# Contains 22 unique values 
len(df['seller_state'].value_counts())

22

In [26]:
# Contains 72 unique values ()
len(df['product_category_name_english'].value_counts())

72

Since here categorical features are nominal and doesn't carry any meaningful order, label encoding could introduce a false relationship between categories. so, i will use one-hot encoding because it prevents the model from interpreting categories as having any numerical ranking

In [27]:
df.columns

Index(['purchase_dayofweek', 'purchase_month', 'purchase_hour',
       'purchase_is_weekend', 'estimated_delivery_days', 'n_items',
       'n_sellers', 'total_price', 'total_freight', 'avg_price',
       'product_weight_g', 'product_length_cm', 'product_height_cm',
       'product_width_cm', 'payment_installments', 'payment_value',
       'payment_type', 'customer_state', 'seller_state',
       'product_category_name_english', 'distance_km', 'same_state',
       'delivery_time_days'],
      dtype='str')

## Train Test Split

In [28]:
skewed_features = [
    'n_items', 'n_sellers', 'total_price', 
    'total_freight', 'avg_price', 'product_weight_g', 
    'product_length_cm', 'product_height_cm',
    'product_width_cm', 'payment_value', 'distance_km'
]

calender_features = [
    'purchase_dayofweek', 'purchase_month', 
    'purchase_hour', 'purchase_is_weekend', 
    'same_state'
]

numeric_features = ['estimated_delivery_days', 'payment_installments',]

categorical_features = [
    'payment_type', 'customer_state', 
    'seller_state', 'product_category_name_english'
]

independent_features = skewed_features + calender_features + numeric_features + categorical_features

In [29]:
from sklearn.model_selection import train_test_split

X = df[independent_features]  
y = np.log1p(df['delivery_time_days'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape)  
print(X_train.columns.tolist())

(77176, 22)
['n_items', 'n_sellers', 'total_price', 'total_freight', 'avg_price', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm', 'payment_value', 'distance_km', 'purchase_dayofweek', 'purchase_month', 'purchase_hour', 'purchase_is_weekend', 'same_state', 'estimated_delivery_days', 'payment_installments', 'payment_type', 'customer_state', 'seller_state', 'product_category_name_english']

In [30]:
y_train.describe()

count    77176.000000
mean         2.424283
std          0.603151
min          0.427497
25%          2.053311
50%          2.420628
75%          2.819413
max          5.350096
Name: delivery_time_days, dtype: float64

In [31]:
y_test.describe()

count    19294.000000
mean         2.413497
std          0.604965
min          0.577380
25%          2.029489
50%          2.406626
75%          2.800756
max          5.204339
Name: delivery_time_days, dtype: float64

## Data Preprocessing using ColumnTransformer

In [32]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer, StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# For skewed features
skew_pipeline = Pipeline(steps=[
    ('log_transform', FunctionTransformer(np.log1p)),
    ('scale', StandardScaler())
])

# For numeric Features
scaling_pipeline = Pipeline(steps=[
    ('scale',StandardScaler())
])

# For categorical features
categorical_pipeline = Pipeline(steps=[
    ('encode', OneHotEncoder(handle_unknown="ignore"))
])

calendar_pipeline = Pipeline(steps=[
    ('passthrough', 'passthrough')  
])


preprocessor = ColumnTransformer(transformers=[
    ("skewness", skew_pipeline, skewed_features),
    ("scaler", scaling_pipeline, numeric_features),
    ("category", categorical_pipeline, categorical_features),
    ("calendar", calendar_pipeline, calender_features),
])

preprocessor

ColumnTransformer(transformers=[('skewness',
                                 Pipeline(steps=[('log_transform',
                                                  FunctionTransformer(func=<ufunc 'log1p'>)),
                                                 ('scale', StandardScaler())]),
                                 ['n_items', 'n_sellers', 'total_price',
                                  'total_freight', 'avg_price',
                                  'product_weight_g', 'product_length_cm',
                                  'product_height_cm', 'product_width_cm',
                                  'payment_value', 'distance_km']),
                                ('scaler',
                                 Pipeline(steps=[(...
                                 ['estimated_delivery_days',
                                  'payment_installments']),
                                ('category',
                                 Pipeline(steps=[('encode',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['payment_type', 'customer_state',
                                  'seller_state',
                                  'product_category_name_english']),
                                ('calendar',
                                 Pipeline(steps=[('passthrough',
                                                  'passthrough')]),
                                 ['purchase_dayofweek', 'purchase_month',
                                  'purchase_hour', 'purchase_is_weekend',
                                  'same_state'])])

In [33]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

In [34]:
print("Preprocessed X_train shape:", X_train_processed.shape)
print("Preprocessed X_test shape:", X_test_processed.shape)

Preprocessed X_train shape: (77176, 144)
Preprocessed X_test shape: (19294, 144)

## Baseline Model Training

In [35]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

In [36]:
models = {
    "Linear Regression": LinearRegression(),
    "KNN": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1),   
    "XGBoost": XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=6, random_state=42, n_jobs=-1), 
}

**Model Training**

In [37]:
trained_models = {}

for name, model in models.items():
    print(f"Training {name}...")
    model.fit(X_train_processed, y_train)
    trained_models[name] = model
    print(f"{name} trained successfully.\n")

Training Linear Regression...
Linear Regression trained successfully.

Training KNN...
KNN trained successfully.

Training Decision Tree...
Decision Tree trained successfully.

Training Random Forest...
Random Forest trained successfully.

Training XGBoost...
XGBoost trained successfully.

**Generate predictions from all models**

In [38]:
predictions = {}

for name, model in trained_models.items():
    predictions[name] = model.predict(X_test_processed)

**Convert predictions back to delivery days**

In [39]:
actual_predictions = {}

for name, y_pred in predictions.items():
    actual_predictions[name] = np.expm1(y_pred)

**Convert y_test back to actual days**

In [40]:
y_test = np.expm1(y_test)

**Baseline model evaluation**

In [41]:
results = []

for name, y_pred in actual_predictions.items():
    
    mae = mean_absolute_error(y_test, y_pred)
    rmse = root_mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    
    results.append({
        "Model": name,
        "MAE": mae,
        "RMSE": rmse,
        "R2 Score": r2
    })

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(by="MAE", ascending=True).reset_index(drop=True)

results_df.round(3)

               Model    MAE    RMSE  R2 Score
0      Random Forest  4.486   7.595     0.335
1            XGBoost  4.489   7.645     0.326
2  Linear Regression  4.860   8.153     0.234
3                KNN  5.064   8.271     0.211
4      Decision Tree  6.564  10.977    -0.389

**Well, i evaluated five baseline regression models and random forest (MAE: 4.486 days, RMSE: 7.595 days, and R²: 0.335) and XGboost (MAE: 4.489 days, RMSE: 7.645 days, and R²: 0.326) performed best. i selected random forest and xgboost as the baseline champion and will now optimize both hyperparameters to improve prediction performance.**

## Hyperparameter Optimization

**Tuned random forest model**

In [42]:
from sklearn.model_selection import RandomizedSearchCV

rf_pipeline = Pipeline([
    ('preprocessor', preprocessor), 
    ('regressor', RandomForestRegressor(random_state=42))
])

rf_params = {
    'regressor__n_estimators'      : [50, 100, 150, 200],
    'regressor__max_depth'         : [1, 2, 3, 5],
    'regressor__min_samples_split' : [2, 3, 5, 8],
    'regressor__min_samples_leaf'  : [1, 2, 4, 6],
}

tuned_rf = RandomizedSearchCV(
    estimator=rf_pipeline,
    param_distributions=rf_params,
    n_iter=20,
    cv=5,
    scoring='neg_mean_absolute_error',
    random_state=42,
    n_jobs=-1,     
    verbose=3
)

tuned_rf.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('skewness',
                                                                               Pipeline(steps=[('log_transform',
                                                                                                FunctionTransformer(func=<ufunc 'log1p'>)),
                                                                                               ('scale',
                                                                                                StandardScaler())]),
                                                                               ['n_items',
                                                                                'n_sellers',
                                                                                'total_price',
                                                                                'total_freight',
                                                                                'avg_price',
                                                                                'product_weight_g',
                                                                                'product_length_cm',
                                                                                'product_height_cm',
                                                                                'product_wid...
                                                                                'purchase_is_weekend',
                                                                                'same_state'])])),
                                             ('regressor',
                                              RandomForestRegressor(random_state=42))]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'regressor__max_depth': [1, 2, 3, 5],
                                        'regressor__min_samples_leaf': [1, 2, 4,
                                                                        6],
                                        'regressor__min_samples_split': [2, 3,
                                                                         5, 8],
                                        'regressor__n_estimators': [50, 100,
                                                                    150, 200]},
                   random_state=42, scoring='neg_mean_absolute_error',
                   verbose=3)

In [43]:
print(tuned_rf.best_params_)
print("best cv mae of tuned random forest:", -tuned_rf.best_score_)

{'regressor__n_estimators': 150, 'regressor__min_samples_split': 2, 'regressor__min_samples_leaf': 6, 'regressor__max_depth': 5}
best cv mae of tuned random forest: 0.35657166234239196

**Tuned xgboost model**

In [45]:
xgb_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', XGBRegressor(random_state=42))
])

xgb_params = {
    'regressor__n_estimators'  : [100, 150, 200, 300, 400],
    'regressor__max_depth'     : [3, 5, 7, 9, 12],
    'regressor__learning_rate' : [0.01, 0.05, 0.1, 0.2, 0.5],
    'regressor__subsample'     : [0.7, 0.85, 1.0],
}

tuned_xgb = RandomizedSearchCV(
    estimator=xgb_pipeline,
    param_distributions=xgb_params,
    n_iter=20,
    cv=5,
    scoring='neg_mean_absolute_error',
    random_state=42,
    n_jobs=1,
    verbose=1
)

tuned_xgb.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('skewness',
                                                                               Pipeline(steps=[('log_transform',
                                                                                                FunctionTransformer(func=<ufunc 'log1p'>)),
                                                                                               ('scale',
                                                                                                StandardScaler())]),
                                                                               ['n_items',
                                                                                'n_sellers',
                                                                                'total_price',
                                                                                'total_freight',
                                                                                'avg_price',
                                                                                'product_weight_g',
                                                                                'product_length_cm',
                                                                                'product_height_cm',
                                                                                'product_wid...
                                                           multi_strategy=None,
                                                           n_estimators=None,
                                                           n_jobs=None,
                                                           num_parallel_tree=None, ...))]),
                   n_iter=20, n_jobs=1,
                   param_distributions={'regressor__learning_rate': [0.01, 0.05,
                                                                     0.1, 0.2,
                                                                     0.5],
                                        'regressor__max_depth': [3, 5, 7, 9,
                                                                 12],
                                        'regressor__n_estimators': [100, 150,
                                                                    200, 300,
                                                                    400],
                                        'regressor__subsample': [0.7, 0.85,
                                                                 1.0]},
                   random_state=42, scoring='neg_mean_absolute_error',
                   verbose=1)

In [46]:
print(tuned_xgb.best_params_)
print("best cv mae of tuned xgb:", -tuned_xgb.best_score_)

{'regressor__subsample': 0.7, 'regressor__n_estimators': 200, 'regressor__max_depth': 9, 'regressor__learning_rate': 0.05}
best cv mae of tuned xgb: 0.32534920220825564

## Final model evaluation

In [47]:
def evaluate(name, tuned_pipeline):
    y_pred = np.expm1(tuned_pipeline.predict(X_test))
    mae  = mean_absolute_error(y_test, y_pred)
    rmse = root_mean_squared_error(y_test, y_pred)
    r2   = r2_score(y_test, y_pred)
    return {"Model": name, "MAE": mae, "RMSE": rmse, "R2 Score": r2}

In [48]:
tuned_results = [
    evaluate("Tuned Random Forest", tuned_rf.best_estimator_),
    evaluate("Tuned XGBoost", tuned_xgb.best_estimator_),
]

In [49]:
tuned_results_df = pd.DataFrame(tuned_results)
tuned_results_df = tuned_results_df.sort_values(by="MAE", ascending=True).reset_index(drop=True)
tuned_results_df.round(3)

                 Model    MAE   RMSE  R2 Score
0        Tuned XGBoost  4.418  7.549     0.343
1  Tuned Random Forest  4.814  8.065     0.250

## Saved best model

In [50]:
import joblib
joblib.dump(tuned_xgb.best_estimator_, "../model/delivero_model.pkl")

['../model/delivero_model.pkl']